### ISSUE TITLE
Alert Pop ups from querys not working on linux headless version

### ISSUE THREAD

**Issue by ghost** [nicko88/HTWebRemoteHost#1]
When using the windows version the pop ups from queries work as intended.
![image](https://github.com/nicko88/HTWebRemoteHost/assets/68743163/9f101143-a2a4-4882-a05f-a679fa60805e)
and in the html there is an alert function in the script part.
![Screenshot 2023-10-31 213638](https://github.com/nicko88/HTWebRemoteHost/assets/68743163/23b1f9d2-4c3a-4153-ab9b-5e306cc9e696)
But when I use the linux version nothing happens and no alert pops up.
The script part of the html is just null
![Screenshot 2023-10-31 213701](https://github.com/nicko88/HTWebRemoteHost/assets/68743163/db9d7a15-ed58-4e37-8363-90ca513d3a72)

**Comment by nicko88** [comment]
Thanks for reporting this bug.

It's fixed now in [v1.9.0.3](https://github.com/nicko88/HTWebRemoteHost/releases/tag/v1.9.0.3)
